version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_SERVER: http://localhost:4000 # use internal Docker network name
    ports:
      - "3000:80"  # expose Nginx on host port 3000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRETKEY=${JWT_SECRETKEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}
      - NODE_ENV=production
      - PORT=4000
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
